server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 445277190723-r8vrjt2lucqe88j19ick2orrl23obch6.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
          facebook:
            client-id: 1142816413130220
            client-secret: 08b92b5be82bbdb73dc4adc90a36707c
            scope:
              - email
              - public_profile

          naver:
            client-id: H2zrQZofLIii2hRJQpoA
            client-secret: 8PJcRWsFzf
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8000/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회워정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌줌



